name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Pull Docker image
      run: docker pull brettviren/wct-testing
    - name: Build
      run: ls -al
